sfg:
  brewery:
    apihost: http://localhost:8080
    customerV1: /api/v1/customer/
    namePath: /name/
    savePath: /savecust
    updatePath: /update/
    deletePath: /delete/
  resttemplate:
    maxTotal: 100
    defaultMaxPerRoute: 20
    requestTimeout: 3000
    socketTimeout: 3000

logging:
  level:
    org:
      apache:
        http: info
